Implement gameover screen (issue #65)
Biscuitmunch/310A1Team2 pull request #66
Opened 2022-09-26 17:03 UTC by HZ991

**Implementation branch for game over screen feature**
close #65 

Complete:
- Basic game over screen module which displays 'Game Over' text, high score, and navigation
- Currently, the screen only displays after space invaders, snake, and pong
- exit button (x) now exits the window instead of returning to the previous screen when clicked

2022-09-26 20:58 UTC, bjur781 commented
Do we maybe want to create a new branch in the main repo and merge this into there? That way everyone can still access it and work on it but we don't risk breaking the build in our release branch?

2022-09-26 21:30 UTC, bjur781 commented on MainGame/Gameover.py
> +                OVER_TEXT = title_font.render("GAME OVER", True, "Red")
Could this OVER_TEXT be taken out of the if statements since its the same in every 'if'?

2022-09-27 06:52 UTC, HZ991 commented on MainGame/Gameover.py
> +                OVER_TEXT = title_font.render("GAME OVER", True, "Red")
this has been changed in the code after the latest commit

2022-09-29 05:02 UTC, cnat307 requested changes

2022-09-29 05:02 UTC, cnat307 commented on MainGame/Gameover.py
> +                    running = False
The design of the game over screen is great, fitting the arcade theme well. Regarding navigation, could the app's exit button be altered to close the entire app when pressed, so that the functionality stays consistent with the implementation within PR #68. Can't wait to see the full game over screen implementation.

2022-09-29 07:52 UTC, HZ991 commented on MainGame/Gameover.py
> +                    running = False
After the latest commit, the window should close upon the exit x button being clicked in the game over screen. This is should be consistent with the implementation in #68

2022-09-29 07:57 UTC, cnat307 approved these changes

2022-09-29 08:50 UTC, merged