Update UI and add level difference
Biscuitmunch/310A1Team2 pull request #89
Opened 2022-10-17 11:54 UTC by hjia095

# Changes
## UI 
  - Add a remain enemy label
  - Change background image when level cleared
## Level Adjustment
 - Num of enemies will grow randomly
 - Speed of enemies will increase as the game goes
 - Chance of enemies shooting will increase as teh game goes
 - Player will regenerate part of missing health when level cleared
 - Player has shooting ability power up when reach certain level (3 stage in total)

2022-10-17 23:05 UTC, bjur781 requested changes
When you die and then replay space invaders, the score remains the same. I think that if you die the score should reset back to 0.
Just that and some nitpicky code styling changes.
It's way more fun to play now with the different levels :)

2022-10-17 23:05 UTC, bjur781 commented on MainGame/Invader/space_invaders.py
> +    os.path.join(resources_path, "ship_yellow.png"))
could this be joined into one line to make the code a bit cleaner?

2022-10-17 23:05 UTC, bjur781 commented on MainGame/Invader/space_invaders.py
> +    os.path.join(resources_path, "laser_yellow.png"))
same here, these could all be on one line which would make them easier to read

2022-10-17 23:05 UTC, bjur781 commented on MainGame/Invader/space_invaders.py
> +        ) + bar_height, self.ship_image.get_width() * health_fraction_calc, bar_height))
could this formatting be cleaned up a bit

2022-10-17 23:05 UTC, bjur781 commented on MainGame/Invader/space_invaders.py
> +            F"ENEMY: {len(enemies)} ", 1, ((255, 255, 255)))
could this all be moved to one line, and could we write 'enemies' rather than 'enemy'? There's usually more than one ship

2022-10-18 01:36 UTC, hjia095 commented
> could this be joined into one line to make the code a bit cleaner?

> same here, these could all be on one line which would make them easier to read

> could this formatting be cleaned up a bit

> could this all be moved to one line, and could we write 'enemies' rather than 'enemy'? There's usually more than one ship

The line separations are caused by IDE auto-formating, will change that

2022-10-18 02:15 UTC, hjia095 commented on MainGame/Invader/space_invaders.py
> +        ) + bar_height, self.ship_image.get_width() * health_fraction_calc, bar_height))
> could this formatting be cleaned up a bit

2022-10-18 02:31 UTC, hjia095 commented
# Changes
## Fix 
 - The problem of score does not reset
## Refactor
 - Reformat codes

2022-10-18 06:59 UTC, bjur781 approved these changes

2022-10-18 07:02 UTC, merged